version: '3.4'

services:

  sqldata:
    image: mcr.microsoft.com/mssql/server 
    environment:
      - SA_PASSWORD=aFbnk#@123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - C:\dados\volumes\sqldata2:/var/opt/mssql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
     - "15672:15672"
     - "5672:5672"

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    environment:
      DbServer: "sqldata"
      DbPort: "1433"
      DbUser: "SA"
      Password: "aFbnk#@123"
      Database: "CtlgDb"
      ConnectionString: "Server=sqldata, 1433;Initial Catalog=CtlgDb;User ID=SA;Password=aFbnk#@123"
      EventBusConnection: "rabbitmq"
      EventBusUserName: "guest"
      EventBusPassword: "guest"
      SubscriptionClientName: "Catalog"
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - sqldata
      - rabbitmq

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    environment:
      EventBusConnection: "rabbitmq"
      EventBusUserName: "guest"
      EventBusPassword: "guest"
      SubscriptionClientName: "Basket"
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    depends_on:
      - rabbitmq

  ordering.backgroundtasks:
    image: ${DOCKER_REGISTRY-}orderingbackgroundtasks
    environment:
      EventBusConnection: "rabbitmq"
      EventBusUserName: "guest"
      EventBusPassword: "guest"
      SubscriptionClientName: "BackgroundTasks"
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.BackgroundTasks/Dockerfile
    depends_on:
      - sqldata
      - rabbitmq

  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGw/Dockerfile
    depends_on:
      - basket.api
      - catalog.api
      - ordering.backgroundtasks
